package aidaban.resources.wsdl.aida;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2014-08-13T12:15:13.940-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "aidaService", 
                  wsdlLocation = "file:/home/mmorales/fuseWorkspace/coppel-soap/src/main/resources/META-INF/wsdl/aida_1.wsdl",
                  targetNamespace = "urn:aidaban/resources/wsdl/aida1") 
public class AidaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:aidaban/resources/wsdl/aida1", "aidaService");
    public final static QName AidaPort = new QName("urn:aidaban/resources/wsdl/aida1", "aidaPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/mmorales/fuseWorkspace/coppel-soap/src/main/resources/META-INF/wsdl/aida.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AidaService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/mmorales/fuseWorkspace/coppel-soap/src/main/resources/META-INF/wsdl/aida.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AidaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AidaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AidaService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AidaPortType
     */
    @WebEndpoint(name = "aidaPort")
    public AidaPortType getAidaPort() {
        return super.getPort(AidaPort, AidaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AidaPortType
     */
    @WebEndpoint(name = "aidaPort")
    public AidaPortType getAidaPort(WebServiceFeature... features) {
        return super.getPort(AidaPort, AidaPortType.class, features);
    }

}
