package aidaban.resources.wsdl.aida;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2014-08-13T12:15:13.909-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "urn:aidaban/resources/wsdl/aida1", name = "aidaPortType")
@XmlSeeAlso({com.coppel.e03.ObjectFactory.class, com.coppel.s03.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AidaPortType {

    @WebResult(name = "doc", targetNamespace = "http://s03.coppel.com", partName = "Parte")
    @WebMethod
    public com.coppel.s03.Doc aida(
        @WebParam(partName = "Parte", name = "doc", targetNamespace = "http://e03.coppel.com")
        com.coppel.e03.Doc parte
    );
}
